name: Module-Signature
version: 0.38
abstract: Module signature file manipulation
author: Autrijus Tang (autrijus@autrijus.org)
license: perl
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.005
  Digest::SHA1: 0
recommends:
  PAR::Dist: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.31
