abstract: Module signature file manipulation
author: Audrey Tang <cpan@audreyt.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.62
license: MIT
name: Module-Signature
no_index: 
  directory: 
    - inc
    - t
recommends: 
  PAR::Dist: 0
requires: 
  perl: 5.005
version: 0.54
